[[constraint]]
  name = "github.com/ugorji/go"
  branch = "master"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[prune]
  go-tests = true
  unused-packages = true
